# Generated by Django 2.2.6 on 2020-05-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('license', 'license'), ('color', 'color'), ('package', 'package')], default='license', max_length=100),
        ),
    ]
