# Generated by Django 2.2.6 on 2020-05-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_variationmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('license', 'license'), ('package', 'package')], default='license', max_length=100),
        ),
    ]
