# Generated by Django 2.2.6 on 2020-05-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200517_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
