# Generated by Django 2.2.6 on 2020-05-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='products',
            new_name='product',
        ),
    ]
